/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shopet;

/**
 *
 * @author Indri
 */

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Barang extends javax.swing.JFrame {

    /**
     * Creates new form Barang
     */
    //public static Integer Updatestok;
        
    DefaultTableModel model;
    
    public Barang() {
        initComponents();
           // Updatestok = Integer.parseInt(Stock.getText());
        /*
        Code untuk membuat nama kolom pada tabel produk
        */

            String [] judul = {"ID Product","Product","Purchase Price","Selling Price","Stock"};
            model = new DefaultTableModel(judul,0);
            tabelproduct.setModel(model);
            tampilkan(); // Methode untuk menampilkan database di GUI
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        databarang = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        IDProduct = new javax.swing.JTextField();
        PurchasePrice = new javax.swing.JTextField();
        Product = new javax.swing.JTextField();
        SellingPrice = new javax.swing.JTextField();
        Stock = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelproduct = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        txtCari = new javax.swing.JTextField();
        search = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        databarang.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        databarang.setForeground(new java.awt.Color(124, 68, 39));
        databarang.setText("Data Product and Stock");
        getContentPane().add(databarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(124, 68, 39));
        jLabel1.setText("Save, Edit and Delete Product Data");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 80, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/PRODUK 64.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, -1, -1));

        btnSave.setBackground(new java.awt.Color(244, 245, 240));
        btnSave.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/SIMPAN 32.png"))); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 490, 130, 50));

        btnEdit.setBackground(new java.awt.Color(244, 245, 240));
        btnEdit.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/EDIT 32.png"))); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        getContentPane().add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 560, 120, 50));

        btnDelete.setBackground(new java.awt.Color(244, 245, 240));
        btnDelete.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/DELETE 32.png"))); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 560, 120, 50));

        btnReset.setBackground(new java.awt.Color(244, 245, 240));
        btnReset.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/RESET 32.png"))); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        getContentPane().add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 560, 120, 50));

        btnHome.setBackground(new java.awt.Color(244, 245, 240));
        btnHome.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/MENU 32.png"))); // NOI18N
        btnHome.setText("Home");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        getContentPane().add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 560, 120, 50));

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel4.setText("ID Product");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 165, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel5.setText("Product");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 235, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel6.setText("Purchase Price");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 305, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel7.setText("Selling Price");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 375, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel8.setText("Stock");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 445, -1, -1));

        IDProduct.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        getContentPane().add(IDProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 221, -1));

        PurchasePrice.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        getContentPane().add(PurchasePrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 221, -1));

        Product.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        getContentPane().add(Product, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 221, -1));

        SellingPrice.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        getContentPane().add(SellingPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 221, -1));

        Stock.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        getContentPane().add(Stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 440, 221, -1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 50, -1));

        tabelproduct.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        tabelproduct.setForeground(new java.awt.Color(0, 0, 0));
        tabelproduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        tabelproduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelproductMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelproduct);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(465, 209, 730, 330));

        jPanel1.setBackground(new java.awt.Color(250, 177, 160));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1260, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 1260, -1));

        txtCari.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        getContentPane().add(txtCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 160, 270, -1));

        search.setBackground(new java.awt.Color(244, 245, 240));
        search.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/loupe.png"))); // NOI18N
        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        getContentPane().add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(1075, 155, 120, 40));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/backg.jpg"))); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1260, 650));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        
        /*
        Masuk ke Page Menu
        */
        
          Menu mn =  new Menu();
          mn.setVisible(true);
          mn.pack();
          mn.setLocationRelativeTo(null);
          mn.setDefaultCloseOperation(Menu.EXIT_ON_CLOSE);
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here: 
        
        /*
        Untuk nge-save ke dalam Database MYSQL shopet
        Jika berhasil akan langsung muncul di tabel GUI
        dan jika ada yang salah atau primary key nya sama maka akan muncul JOptionPane
        */
        
          try {
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/shopet2","root","");
            cn.createStatement().executeUpdate("insert into product values"+
                                               "('"+IDProduct.getText()+
                                               "','"+Product.getText()+
                                               "','"+PurchasePrice.getText()+
                                               "','"+SellingPrice.getText()+
                                               "','"+Stock.getText()+"')");
            JOptionPane.showMessageDialog(null, "Product added successfully");
            tampilkan(); //Methode untuk menampilkan ke GUI
            reset(); //untuk membersihkan data inputan di textfield setelah di save
            
          } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Some are not filled in, Please check again !!");
          }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        
        /*
        Button untuk mengedit bila ada data yang ingin diubah atau ada yang salah
        */
          try {
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/shopet2","root","");
            cn.createStatement().executeUpdate("update product set "
                                               + "Product ='"+Product.getText()+
                                               "',PurchasePrice ='"+PurchasePrice.getText()+
                                               "',SellingPrice ='"+SellingPrice.getText()+
                                               "',Stock ='"+Stock.getText()+
                                               "' where IDProduct ='"+IDProduct.getText()+"'");           
            JOptionPane.showMessageDialog(null, "Successful");
            tampilkan(); // Methode Untuk menampilkan ke tabel GUI
            reset(); // Untuk membersihkan data inputan di textfield setelah di save
            
          } catch (SQLException ex) {
            Logger.getLogger(Barang.class.getName()).log(Level.SEVERE, null, ex);            
          }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:  
        
        /*
        Untuk menghapus data yang tidak dibutuhkan lagi, akan otomatis terhapus juga data yang ada di Dtabase MYSQL
        */
        
          try {
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/shopet2","root","");
            cn.createStatement().executeUpdate("delete from product where IDProduct = '"+IDProduct.getText()+"'");
            JOptionPane.showMessageDialog(null, "Successful");
            tampilkan(); // Methode untuk menampilkan ke tabel GUI
            reset(); // Untuk memberdihkan data inputan di textfield setelah di save
          } catch (SQLException ex) {
            Logger.getLogger(Barang.class.getName()).log(Level.SEVERE, null, ex);
          }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void tabelproductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelproductMouseClicked
        // TODO add your handling code here:
        
        /* 
        Buat Munculin Isi tabel di text field saat tabel di klik
        */
        
          int i = tabelproduct.getSelectedRow();
        
          if (i>-1){
            IDProduct.setText(model.getValueAt(i,0).toString());
            Product.setText(model.getValueAt(i,1).toString());
            PurchasePrice.setText(model.getValueAt(i,2).toString());
            SellingPrice.setText(model.getValueAt(i,3).toString());
            Stock.setText(model.getValueAt(i,4).toString());
          }
    }//GEN-LAST:event_tabelproductMouseClicked

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        
        /* 
        Mau me-reset atau kosongin text field 
        */
          reset();
    }//GEN-LAST:event_btnResetActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        
        /*
        Button search untuk mencari data yang diinginkan secara cepat
        pencarian berdasarkan IDPRODUCT dan Product (nama product)
        */
        
          try {
            int row = tabelproduct.getRowCount();
            for(int a= 0; a<row;a++){
                model.removeRow(0);}
            
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/shopet2","root","");
            ResultSet rs = cn.createStatement().executeQuery("SELECT * FROM product where IDProduct like '%" +
                                                             txtCari.getText()+"%'" + "or Product like '%" + 
                                                             txtCari.getText() + "%'");
                while(rs.next()) {
                    String data [] = {rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5)};
                    model.addRow(data);
                }
          } catch (SQLException ex) {
            Logger.getLogger(Barang.class.getName()).log(Level.SEVERE, null, ex);
          }
    }//GEN-LAST:event_searchActionPerformed
    
    private void reset(){
        // Untuk kosongin text Field        
        IDProduct.setText("");
        Product.setText("");
        PurchasePrice.setText("");
        SellingPrice.setText("");
        Stock.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Barang().setVisible(true);
                Barang Bar = new Barang();
              Bar.setSize(1258, 645);
          }
       });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JTextField IDProduct;
    private javax.swing.JTextField Product;
    private javax.swing.JTextField PurchasePrice;
    private javax.swing.JTextField SellingPrice;
    private javax.swing.JTextField Stock;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel databarang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton search;
    private javax.swing.JTable tabelproduct;
    private javax.swing.JTextField txtCari;
    // End of variables declaration//GEN-END:variables

    /*
    Membuat Method "tampilkan" untuk menampilkan data Barang di GUI setelah disave ke database MYSQL-product
    */
    
    private void tampilkan() {
       // untuk menambahkan baris pada tabel
       int row = tabelproduct.getRowCount();
       for(int a= 0; a<row;a++){
           model.removeRow(0);}
       
           try {
               Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/shopet2","root","");
               ResultSet rs = cn.createStatement().executeQuery("SELECT * FROM product");
                while(rs.next()) {
                    String data [] = {rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5)};
                    model.addRow(data);
                }
           } catch (SQLException ex) {
               Logger.getLogger(Barang.class.getName()).log(Level.SEVERE, null, ex);
           }
    }
}




