/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shopet;

import java.io.File;
import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import javax.swing.JOptionPane;
import net.sf.jasperreports.view.JasperViewer;
/**
 *
 * @author Indri
 */
public class EmployeeReport extends javax.swing.JFrame {

    /**
     * Creates new form EmployeeReport
     */
    
    DefaultTableModel model;
    
    public EmployeeReport() {
        initComponents();
            String [] judul = {"ID Employee","Name Employee","Gender","Telephone Number","Sallary","Address"};
            model = new DefaultTableModel(judul,0);
            tabelEmployee.setModel(model);
            Tampil(); // Methode untuk menampilkan database di GUI
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCari = new javax.swing.JTextField();
        btnHome = new javax.swing.JButton();
        search = new javax.swing.JButton();
        btnprint = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelEmployee = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCari.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        getContentPane().add(txtCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 167, 260, -1));

        btnHome.setBackground(new java.awt.Color(244, 245, 240));
        btnHome.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/MENU 32.png"))); // NOI18N
        btnHome.setText("Home");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        getContentPane().add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 570, 130, 50));

        search.setBackground(new java.awt.Color(244, 245, 240));
        search.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/loupe.png"))); // NOI18N
        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        getContentPane().add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 160, 120, 40));

        btnprint.setBackground(new java.awt.Color(244, 245, 240));
        btnprint.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        btnprint.setText("PRINT");
        btnprint.setDoubleBuffered(true);
        btnprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprintActionPerformed(evt);
            }
        });
        getContentPane().add(btnprint, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 570, 150, 50));

        tabelEmployee.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        tabelEmployee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        tabelEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelEmployeeMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelEmployee);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 1120, 350));

        jPanel1.setBackground(new java.awt.Color(250, 177, 160));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(124, 68, 39));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/KARYAWAN 64.png"))); // NOI18N
        jLabel1.setText("Employee Reports");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(481, 481, 481)
                .addComponent(jLabel1)
                .addContainerGap(444, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1260, 110));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/backg.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1260, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabelEmployeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelEmployeeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tabelEmployeeMouseClicked

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:

        /*
        Button search untuk mencari data yang diinginkan secara cepat
        pencarian berdasarkan IDEMPLOYEE dan Nama Karyawan
        */

        try {
            int row = tabelEmployee.getRowCount();
            for(int a= 0; a<row;a++){
                model.removeRow(0);
            }
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/shopet2","root","");
            ResultSet rs = cn.createStatement().executeQuery("SELECT * FROM employee where IDEmployee like '%" +
                txtCari.getText()+"%'" + "or NameEmp like '%" +
                txtCari.getText() + "%'");
            while(rs.next()) {
                String data [] = {rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6)};
                model.addRow(data);
            }
        } catch (SQLException ex) {
            Logger.getLogger(EmployeeReport.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_searchActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:

        /*
        Masuk ke Page Menu
        */

        Menu mn =  new Menu();
        mn.setVisible(true);
        mn.pack();
        mn.setLocationRelativeTo(null);
        mn.setDefaultCloseOperation(Menu.EXIT_ON_CLOSE);
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprintActionPerformed
        // TODO add your handling code here:
        try {
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/shopet2","root","");
            File file = new File ("src/Laporan/Employee.jasper");
            JasperPrint jp = JasperFillManager.fillReport(file.getPath(),null,cn);
            JasperViewer.viewReport(jp,false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data Can't be printed !!!"+"\n"+e.getMessage(), "Print Data",
                javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnprintActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeReport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnprint;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton search;
    private javax.swing.JTable tabelEmployee;
    private javax.swing.JTextField txtCari;
    // End of variables declaration//GEN-END:variables

private void Tampil() {
        // untuk menambahkan baris pada tabel
        int row = tabelEmployee.getRowCount();
        for(int a= 0; a<row;a++){
            model.removeRow(0);}
           
          try {
              Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/shopet2","root","");
              ResultSet rs = cn.createStatement().executeQuery("SELECT * FROM employee");
                while(rs.next()) {
                    String data [] = {rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6)};
                    model.addRow(data);}
          } catch (SQLException ex) {
            Logger.getLogger(EmployeeReport.class.getName()).log(Level.SEVERE, null, ex);
          }
    }
}
