/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shopet;

/**
 *
 * @author Indri
 */

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Konsumen extends javax.swing.JFrame {

    /**
     * Creates new form Konsumen
     */
    
    DefaultTableModel model;
    
    public Konsumen() {
        initComponents();
        
        /*
        Code untuk membuat nama kolom pada tabel produk
        */
        
            String [] judul = {"ID Customer","Name Customer","Telephone Number","Address"};
            model = new DefaultTableModel(judul,0);
            tabelCust.setModel(model);
            Tampil(); // Methode untuk menampilkan database di GUI
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        search = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        karyawan = new javax.swing.JLabel();
        konsumennama = new javax.swing.JLabel();
        AlamatKonsumen = new javax.swing.JLabel();
        IDCustomer = new javax.swing.JTextField();
        txtCari = new javax.swing.JTextField();
        Name = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Address = new javax.swing.JTextArea();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelCust = new javax.swing.JTable();
        noTlpn = new javax.swing.JLabel();
        TelephoneNumber = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        search.setBackground(new java.awt.Color(244, 245, 240));
        search.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/loupe.png"))); // NOI18N
        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        getContentPane().add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 160, 120, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/KONSUMEN 64.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(413, 38, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(124, 68, 39));
        jLabel2.setText("Data Customer Shopet");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 38, -1, -1));

        karyawan.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        karyawan.setText("ID Customer");
        getContentPane().add(karyawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, -1, -1));

        konsumennama.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        konsumennama.setText("Name");
        getContentPane().add(konsumennama, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, -1, -1));

        AlamatKonsumen.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        AlamatKonsumen.setText("Address");
        getContentPane().add(AlamatKonsumen, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, -1, -1));

        IDCustomer.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        getContentPane().add(IDCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 230, -1));

        txtCari.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        getContentPane().add(txtCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 167, 230, -1));

        Name.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        getContentPane().add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 230, -1));

        Address.setColumns(20);
        Address.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        Address.setRows(5);
        jScrollPane1.setViewportView(Address);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 400, 230, 210));

        btnEdit.setBackground(new java.awt.Color(244, 245, 240));
        btnEdit.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/EDIT 32.png"))); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        getContentPane().add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 560, 120, 50));

        btnHapus.setBackground(new java.awt.Color(244, 245, 240));
        btnHapus.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/DELETE 32.png"))); // NOI18N
        btnHapus.setText("Delete");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        getContentPane().add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 560, 120, 50));

        btnReset.setBackground(new java.awt.Color(244, 245, 240));
        btnReset.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/RESET 32.png"))); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        getContentPane().add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 560, 120, 50));

        btnHome.setBackground(new java.awt.Color(244, 245, 240));
        btnHome.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/MENU 32.png"))); // NOI18N
        btnHome.setText("Home");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        getContentPane().add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 560, 120, 50));

        btnSimpan.setBackground(new java.awt.Color(244, 245, 240));
        btnSimpan.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        btnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/SIMPAN 32.png"))); // NOI18N
        btnSimpan.setText("Save");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        getContentPane().add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 560, 130, 50));

        tabelCust.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelCust.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelCustMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelCust);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 220, 720, 320));

        noTlpn.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        noTlpn.setText("Telephone Number");
        getContentPane().add(noTlpn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, -1, -1));

        TelephoneNumber.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        getContentPane().add(TelephoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, 230, -1));

        jPanel1.setBackground(new java.awt.Color(250, 177, 160));

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(124, 68, 39));
        jLabel3.setText("Save, Edit and Delete Customer Data");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(506, 506, 506)
                .addComponent(jLabel3)
                .addContainerGap(552, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(24, 24, 24))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 20, 1270, -1));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/backg.jpg"))); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1260, 650));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        
        /*
        Masuk ke Page Menu
        */
        
        Menu mn =  new Menu();
        mn.setVisible(true);
        mn.pack();
        mn.setLocationRelativeTo(null);
        mn.setDefaultCloseOperation(Menu.EXIT_ON_CLOSE);
    }//GEN-LAST:event_btnHomeActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        
         /*
        Button search untuk mencari data yang diinginkan secara cepat
        pencarian berdasarkan IDCUSTOMER dan Nama Customer
        */
         
            try {
                int row = tabelCust.getRowCount();
                for(int a= 0; a<row;a++){
                    model.removeRow(0);
                }
                Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/shopet2","root","");
                ResultSet rs = cn.createStatement().executeQuery("SELECT * FROM customer where IDCustomer like '%" +
                                                                 txtCari.getText()+"%'" + "or NameCust like '%" + 
                                                                 txtCari.getText() + "%'");
                while(rs.next()) {
                    String data [] = {rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4)};
                    model.addRow(data);
                }
            } catch (SQLException ex) {
                Logger.getLogger(Karyawan.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_searchActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        
        /* 
        Mau me-reset atau kosongin text field 
        */
        
            reset();
    }//GEN-LAST:event_btnResetActionPerformed

    private void tabelCustMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelCustMouseClicked
        // TODO add your handling code here:
        
        /* 
        Buat Munculin Isi tabel di text field saat tabel di klik
        */
        
            int i = tabelCust.getSelectedRow();

            if (i>-1){
                IDCustomer.setText(model.getValueAt(i,0).toString());
                Name.setText(model.getValueAt(i,1).toString());
                TelephoneNumber.setText(model.getValueAt(i,3).toString());
                Address.setText(model.getValueAt(i,2).toString());
            }
    }//GEN-LAST:event_tabelCustMouseClicked

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        
        /*
        Untuk nge-save ke dalam Database MYSQL shopet
        Jika berhasil akan langsung muncul di tabel GUI
        dan jika ada yang salah atau primary key nya sama maka akan muncul JOptionPane
        */
        
            try {
                Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/shopet2","root","");
                cn.createStatement().executeUpdate("insert into customer values"+
                                                   "('"+IDCustomer.getText()+
                                                   "','"+Name.getText()+
                                                   "','"+Address.getText()+
                                                   "','"+TelephoneNumber.getText()+"')");
                Tampil(); //Methode untuk menampilkan ke GUI
                reset(); //untuk membersihkan data inputan di textfield setelah di save
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Some are not filled in, Please check again !!");
            }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        
        /*
        Button untuk mengedit bila ada data yang ingin diubah atau ada yang salah
        */
        
            try {
                Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/shopet2","root","");
                cn.createStatement().executeUpdate("update customer set "
                                                   + "NameCust ='"+Name.getText()+
                                                   "',Address ='"+Address.getText()+
                                                   "',TelephoneNumber ='"+TelephoneNumber.getText()+
                                                   "' where IDCustomer ='"+IDCustomer.getText()+"'");
                Tampil(); //Methode untuk menampilkan ke GUI
                JOptionPane.showMessageDialog(null, "Successful");
                reset(); //untuk membersihkan data inputan di textfield setelah di save
            } catch (SQLException ex) {
                Logger.getLogger(Konsumen.class.getName()).log(Level.SEVERE, null, ex);            
            }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        
        /*
        Untuk menghapus data yang tidak dibutuhkan lagi, akan otomatis terhapus juga data yang ada di Dtabase MYSQL
        */
        
            try {
                Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/shopet2","root","");
                cn.createStatement().executeUpdate("delete from customer where IDCustomer = '"+IDCustomer.getText()+"'");
                Tampil(); //Methode untuk menampilkan ke GUI
                JOptionPane.showMessageDialog(null, "Successful");
                reset(); //untuk membersihkan data inputan di textfield setelah di save
            } catch (SQLException ex) {
                Logger.getLogger(Konsumen.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_btnHapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Konsumen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Konsumen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Konsumen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Konsumen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Konsumen().setVisible(true);
            }
        });
    }
    
    private void reset(){
         /* 
        Mau me-reset atau kosongin text field 
        */
         
        IDCustomer.setText("");
        Name.setText("");
        TelephoneNumber.setText("");
        Address.setText("");
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Address;
    private javax.swing.JLabel AlamatKonsumen;
    private javax.swing.JLabel Background;
    private javax.swing.JTextField IDCustomer;
    private javax.swing.JTextField Name;
    private javax.swing.JTextField TelephoneNumber;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel karyawan;
    private javax.swing.JLabel konsumennama;
    private javax.swing.JLabel noTlpn;
    private javax.swing.JButton search;
    private javax.swing.JTable tabelCust;
    private javax.swing.JTextField txtCari;
    // End of variables declaration//GEN-END:variables

    /*
    Membuat Method "Tampil" untuk menampilkan data Konsumen di GUI setelah disave ke database MYSQL-customer
    */
    
    private void Tampil() {
        // untuk menambahkan baris pada tabel
        int row = tabelCust.getRowCount();
        for(int a= 0; a<row;a++){
            model.removeRow(0);
        }
           try {
               Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/shopet2","root","");
               ResultSet rs = cn.createStatement().executeQuery("SELECT * FROM customer");
                while(rs.next()) {
                    String data [] = {rs.getString(1),rs.getString(2),rs.getString(4),rs.getString(3)};
                    model.addRow(data);}
            } catch (SQLException ex) {
               Logger.getLogger(Konsumen.class.getName()).log(Level.SEVERE, null, ex);
            }
    }
    
}
