/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shopet;

import javax.swing.JOptionPane;

/**
 *
 * @author Indri
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btnlogout = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnBarang = new javax.swing.JButton();
        btnKaryawan = new javax.swing.JButton();
        btnKonsumen = new javax.swing.JButton();
        btnTransaksi = new javax.swing.JButton();
        btnLaporan = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 1, 64)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(124, 68, 39));
        jLabel2.setText("SISTEM INFORMASI SHOPET");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, -1, -1));

        btnlogout.setBackground(new java.awt.Color(244, 245, 240));
        btnlogout.setFont(new java.awt.Font("Tw Cen MT", 1, 16)); // NOI18N
        btnlogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/cross.png"))); // NOI18N
        btnlogout.setText("Log Out");
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });
        getContentPane().add(btnlogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 16, -1, 45));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/ICONshopet.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1016, 231, -1, -1));

        btnBarang.setBackground(new java.awt.Color(244, 245, 240));
        btnBarang.setFont(new java.awt.Font("Tw Cen MT", 1, 26)); // NOI18N
        btnBarang.setForeground(new java.awt.Color(124, 68, 39));
        btnBarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/PRODUK 64.png"))); // NOI18N
        btnBarang.setText("Product");
        btnBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBarangActionPerformed(evt);
            }
        });
        getContentPane().add(btnBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 547, 230, 85));

        btnKaryawan.setBackground(new java.awt.Color(244, 245, 240));
        btnKaryawan.setFont(new java.awt.Font("Tw Cen MT", 1, 26)); // NOI18N
        btnKaryawan.setForeground(new java.awt.Color(124, 68, 39));
        btnKaryawan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/KARYAWAN 64.png"))); // NOI18N
        btnKaryawan.setText("Employee");
        btnKaryawan.setToolTipText("");
        btnKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKaryawanActionPerformed(evt);
            }
        });
        getContentPane().add(btnKaryawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 547, 235, 85));

        btnKonsumen.setBackground(new java.awt.Color(244, 245, 240));
        btnKonsumen.setFont(new java.awt.Font("Tw Cen MT", 1, 26)); // NOI18N
        btnKonsumen.setForeground(new java.awt.Color(124, 68, 39));
        btnKonsumen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/KONSUMEN 64.png"))); // NOI18N
        btnKonsumen.setText("Customer");
        btnKonsumen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKonsumenActionPerformed(evt);
            }
        });
        getContentPane().add(btnKonsumen, new org.netbeans.lib.awtextra.AbsoluteConstraints(515, 547, 230, 85));

        btnTransaksi.setBackground(new java.awt.Color(244, 245, 240));
        btnTransaksi.setFont(new java.awt.Font("Tw Cen MT", 1, 26)); // NOI18N
        btnTransaksi.setForeground(new java.awt.Color(124, 68, 39));
        btnTransaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/PENJUALAN 64.png"))); // NOI18N
        btnTransaksi.setText("Transaction");
        btnTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransaksiActionPerformed(evt);
            }
        });
        getContentPane().add(btnTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(757, 547, 230, 85));

        btnLaporan.setBackground(new java.awt.Color(244, 245, 240));
        btnLaporan.setFont(new java.awt.Font("Tw Cen MT", 1, 26)); // NOI18N
        btnLaporan.setForeground(new java.awt.Color(124, 68, 39));
        btnLaporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/LAPORAN 64.png"))); // NOI18N
        btnLaporan.setText("Report");
        btnLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaporanActionPerformed(evt);
            }
        });
        getContentPane().add(btnLaporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(999, 547, 230, 85));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/backg.jpg"))); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1260, 650));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
        // TODO add your handling code here:
        
        /* 
        Keluar dari menu utama dan menampilkan page login lagi
        */
        
          Login log =  new Login();
          log.setVisible(true);
          log.pack();
          log.setLocationRelativeTo(null);
          log.setDefaultCloseOperation(Login.EXIT_ON_CLOSE);
          JOptionPane.showMessageDialog(null, "Thankyou for a good job today");
    }//GEN-LAST:event_btnlogoutActionPerformed

    private void btnLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaporanActionPerformed
        // TODO add your handling code here:
        
        /*
        Untuk Masuk Ke menu Laporan
        */
        
          Laporan lp =  new Laporan();
          lp.setVisible(true);
          lp.pack();
          lp.setLocationRelativeTo(null);
          lp.setDefaultCloseOperation(Laporan.EXIT_ON_CLOSE);
    }//GEN-LAST:event_btnLaporanActionPerformed

    private void btnBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBarangActionPerformed
        // TODO add your handling code here:
       
        /*
        Untuk Masuk ke Menu Barang
        */
        
          Barang bar =  new Barang();
          bar.setVisible(true);
          bar.pack();
          bar.setLocationRelativeTo(null);
          bar.setDefaultCloseOperation(Barang.EXIT_ON_CLOSE);
    }//GEN-LAST:event_btnBarangActionPerformed

    private void btnKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKaryawanActionPerformed
        // TODO add your handling code here:
        
        /*
        Masuk ke menu Karyawan
        */
        
          Karyawan kar =  new Karyawan();
          kar.setVisible(true);
          kar.pack();
          kar.setLocationRelativeTo(null);
          kar.setDefaultCloseOperation(Karyawan.EXIT_ON_CLOSE);
    }//GEN-LAST:event_btnKaryawanActionPerformed

    private void btnKonsumenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKonsumenActionPerformed
        // TODO add your handling code here:
        
        /*
        Masuk ke menu Konsumen
        */
        
          Konsumen kn =  new Konsumen();
          kn.setVisible(true);
          kn.pack();
          kn.setLocationRelativeTo(null);
          kn.setDefaultCloseOperation(Konsumen.EXIT_ON_CLOSE);
    }//GEN-LAST:event_btnKonsumenActionPerformed

    private void btnTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransaksiActionPerformed
        // TODO add your handling code here:
        
        /*
        Masuk ke menu Transaksi
        */
         
          TansaksiPenjualan tr = new TansaksiPenjualan();
          tr.setVisible(true);
          tr.pack();
          tr.setLocationRelativeTo(null);
          tr.setDefaultCloseOperation(Transaksi.EXIT_ON_CLOSE);
    }//GEN-LAST:event_btnTransaksiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
                Menu mn = new Menu();
                mn.setSize(1258, 645);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton btnBarang;
    private javax.swing.JButton btnKaryawan;
    private javax.swing.JButton btnKonsumen;
    private javax.swing.JButton btnLaporan;
    private javax.swing.JButton btnTransaksi;
    private javax.swing.JButton btnlogout;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
