/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shopet;

import java.io.File;
import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import javax.swing.JOptionPane;
import net.sf.jasperreports.view.JasperViewer;
/**
 *
 * @author Indri
 */
public class ProductReport extends javax.swing.JFrame {

    /**
     * Creates new form ProductReport
     */
    
    DefaultTableModel model;
    
    public ProductReport() {
        initComponents();
            String [] judul = {"ID Product","Product","Purchase Price","Selling Price","Stock"};
            model = new DefaultTableModel(judul,0);
            tabelproduct.setModel(model);
            tampilkan();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCari = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelproduct = new javax.swing.JTable();
        search = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnprint = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCari.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        getContentPane().add(txtCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 167, 270, -1));

        jButton1.setBackground(new java.awt.Color(244, 245, 240));
        jButton1.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/LAPORAN 24.png"))); // NOI18N
        jButton1.setText("Report Menu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 570, -1, 50));

        btnHome.setBackground(new java.awt.Color(244, 245, 240));
        btnHome.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/MENU 32.png"))); // NOI18N
        btnHome.setText("Home");
        btnHome.setToolTipText("");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        getContentPane().add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 571, 120, 50));

        tabelproduct.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        tabelproduct.setForeground(new java.awt.Color(0, 0, 0));
        tabelproduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        tabelproduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelproductMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelproduct);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 1020, 350));

        search.setBackground(new java.awt.Color(244, 245, 240));
        search.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/loupe.png"))); // NOI18N
        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        getContentPane().add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 160, 120, 40));

        jPanel1.setBackground(new java.awt.Color(250, 177, 160));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(124, 68, 39));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/PRODUK 64.png"))); // NOI18N
        jLabel1.setText("PRODUCT REPORT");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(445, 445, 445)
                .addComponent(jLabel1)
                .addContainerGap(464, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1260, 110));

        btnprint.setBackground(new java.awt.Color(244, 245, 240));
        btnprint.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        btnprint.setIcon(new javax.swing.ImageIcon("C:\\Users\\Indri\\Downloads\\printer.png")); // NOI18N
        btnprint.setText("Print");
        btnprint.setDoubleBuffered(true);
        btnprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprintActionPerformed(evt);
            }
        });
        getContentPane().add(btnprint, new org.netbeans.lib.awtextra.AbsoluteConstraints(995, 570, 150, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/backg.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1260, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabelproductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelproductMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tabelproductMouseClicked

    private void btnprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprintActionPerformed
        // TODO add your handling code here:
        try {
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/shopet2","root","");
            File file = new File ("src/Laporan/Product.jasper");
            JasperPrint jp = JasperFillManager.fillReport(file.getPath(),null,cn);
            JasperViewer.viewReport(jp,false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data Can't be printed !!!"+"\n"+e.getMessage(), "Print Data",
                javax.swing.JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnprintActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:

        /*
        Button search untuk mencari data yang diinginkan secara cepat
        pencarian berdasarkan IDPRODUCT dan Product (nama product)
        */

        try {
            int row = tabelproduct.getRowCount();
            for(int a= 0; a<row;a++){
                model.removeRow(0);}

            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/shopet2","root","");
            ResultSet rs = cn.createStatement().executeQuery("SELECT * FROM product where IDProduct like '%" +
                txtCari.getText()+"%'" + "or Product like '%" +
                txtCari.getText() + "%'");
            while(rs.next()) {
                String data [] = {rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5)};
                model.addRow(data);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Barang.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_searchActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        // Pergi ke Page Menu
        Menu mn =  new Menu();
        mn.setVisible(true);
        mn.pack();
        mn.setLocationRelativeTo(null);
        mn.setDefaultCloseOperation(Menu.EXIT_ON_CLOSE);
    }//GEN-LAST:event_btnHomeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Laporan lp =  new Laporan();
        lp.setVisible(true);
        lp.pack();
        lp.setLocationRelativeTo(null);
        lp.setDefaultCloseOperation(Menu.EXIT_ON_CLOSE);

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductReport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnprint;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton search;
    private javax.swing.JTable tabelproduct;
    private javax.swing.JTextField txtCari;
    // End of variables declaration//GEN-END:variables

    private void tampilkan() {
       // untuk menambahkan baris pada tabel
       int row = tabelproduct.getRowCount();
       for(int a= 0; a<row;a++){
           model.removeRow(0);}
       
           try {
               Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/shopet2","root","");
               ResultSet rs = cn.createStatement().executeQuery("SELECT * FROM product");
                while(rs.next()) {
                    String data [] = {rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5)};
                    model.addRow(data);
                }
           } catch (SQLException ex) {
               Logger.getLogger(Barang.class.getName()).log(Level.SEVERE, null, ex);
           }
    }
}
