/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shopet;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Indri
 */
public class TansaksiPenjualan extends javax.swing.JFrame {
    
        int Hrg;
        int Buy;
        int pay;
        int JumlahBayar;
        int Kembalian;
        int TotalBelanja;
        
    /**
     * Creates new form TansaksiPenjualan
     */
    
    DefaultTableModel model;
    
    public TansaksiPenjualan() {
        initComponents();
        IDEmp.setText(Login.namakar); // Buat Masukkin nama kita Otomatis
        noTransAuto();
        ComboBoxCust();
        ComboBoxProduct();
        
        AllTotal();
        
        /*
        Code untuk membuat nama kolom pada tabel produk
        */
        
            String [] judul = {"ID Transaction", "ID Employee", "ID Customer", "ID Product", "QTY", "Sub Total"};
            model = new DefaultTableModel(judul,0);
            TblTrans.setModel(model);
            //Tampil();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        IDAuto = new javax.swing.JTextField();
        IDCustAuto = new javax.swing.JTextField();
        ComboCust = new javax.swing.JComboBox<>();
        ComboProduct = new javax.swing.JComboBox<>();
        IDEmp = new javax.swing.JTextField();
        ShowIDProduct = new javax.swing.JTextField();
        ShowPrice = new javax.swing.JTextField();
        Beli = new javax.swing.JTextField();
        SubTotal = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblTrans = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        AllTotal = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        CashMoney = new javax.swing.JTextField();
        Changes = new javax.swing.JLabel();
        btnPrint = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        btnEdit1 = new javax.swing.JButton();
        jTextField9 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        ShowStock = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(250, 177, 160));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/PENJUALAN 64.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(124, 68, 39));
        jLabel2.setText("Transaction / Cashier Shopet");

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(124, 68, 39));
        jLabel3.setText("Welcome and Happy Shopping");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(395, 395, 395)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addContainerGap(368, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(3, 3, 3)
                        .addComponent(jLabel3))
                    .addComponent(jLabel1))
                .addGap(15, 15, 15))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1270, -1));

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel4.setText("ID Transaction");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 164, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel5.setText("ID Employee");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 280, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel6.setText("Product");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel7.setText("Customer");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 223, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel8.setText("Price");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 398, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel9.setText("QTY");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 398, 40, -1));

        jLabel10.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel10.setText("Total");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 398, 50, -1));

        IDAuto.setEditable(false);
        IDAuto.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        IDAuto.setForeground(new java.awt.Color(204, 204, 204));
        IDAuto.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        getContentPane().add(IDAuto, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 110, -1));

        IDCustAuto.setEditable(false);
        IDCustAuto.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        IDCustAuto.setForeground(new java.awt.Color(204, 204, 204));
        getContentPane().add(IDCustAuto, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 218, 120, -1));

        ComboCust.setFont(new java.awt.Font("Tw Cen MT", 1, 17)); // NOI18N
        ComboCust.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All Cust" }));
        ComboCust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboCustActionPerformed(evt);
            }
        });
        getContentPane().add(ComboCust, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 218, 125, -1));

        ComboProduct.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        ComboProduct.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All Products" }));
        ComboProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboProductActionPerformed(evt);
            }
        });
        getContentPane().add(ComboProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 334, 295, -1));

        IDEmp.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        getContentPane().add(IDEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 276, 110, -1));

        ShowIDProduct.setEditable(false);
        ShowIDProduct.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        ShowIDProduct.setForeground(new java.awt.Color(204, 204, 204));
        getContentPane().add(ShowIDProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 334, 110, -1));

        ShowPrice.setEditable(false);
        ShowPrice.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        ShowPrice.setForeground(new java.awt.Color(0, 0, 0));
        ShowPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowPriceActionPerformed(evt);
            }
        });
        getContentPane().add(ShowPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 392, 110, -1));

        Beli.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        Beli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BeliActionPerformed(evt);
            }
        });
        Beli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                BeliKeyReleased(evt);
            }
        });
        getContentPane().add(Beli, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 392, 50, -1));

        SubTotal.setEditable(false);
        SubTotal.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        getContentPane().add(SubTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 392, 110, -1));

        TblTrans.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        jScrollPane1.setViewportView(TblTrans);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 500, 1180, 150));

        jLabel11.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel11.setText("All Total");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 155, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel12.setText("Cash");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 270, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel13.setText("Money Changes");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 270, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        AllTotal.setFont(new java.awt.Font("Tw Cen MT", 1, 52)); // NOI18N
        AllTotal.setForeground(new java.awt.Color(0, 204, 51));

        jLabel15.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 204, 51));
        jLabel15.setText("Rp");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AllTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AllTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 180, 340, 80));

        CashMoney.setFont(new java.awt.Font("Tw Cen MT", 1, 28)); // NOI18N
        CashMoney.setForeground(new java.awt.Color(102, 102, 102));
        CashMoney.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CashMoneyKeyReleased(evt);
            }
        });
        getContentPane().add(CashMoney, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 293, 150, -1));

        Changes.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        Changes.setForeground(new java.awt.Color(0, 51, 204));
        getContentPane().add(Changes, new org.netbeans.lib.awtextra.AbsoluteConstraints(1066, 293, 150, 40));

        btnPrint.setBackground(new java.awt.Color(244, 245, 240));
        btnPrint.setFont(new java.awt.Font("Tw Cen MT", 1, 16)); // NOI18N
        btnPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/printer.png"))); // NOI18N
        btnPrint.setText("Print");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        getContentPane().add(btnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 349, 100, 43));

        btnHapus.setBackground(new java.awt.Color(244, 245, 240));
        btnHapus.setFont(new java.awt.Font("Tw Cen MT", 1, 16)); // NOI18N
        btnHapus.setIcon(new javax.swing.ImageIcon("C:\\Users\\Indri\\Downloads\\delete.png")); // NOI18N
        btnHapus.setText("Delete");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        getContentPane().add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(1013, 398, 100, 43));

        btnReset.setBackground(new java.awt.Color(244, 245, 240));
        btnReset.setFont(new java.awt.Font("Tw Cen MT", 1, 16)); // NOI18N
        btnReset.setIcon(new javax.swing.ImageIcon("C:\\Users\\Indri\\Downloads\\recycle.png")); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        getContentPane().add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 398, 100, 43));

        btnHome.setBackground(new java.awt.Color(244, 245, 240));
        btnHome.setFont(new java.awt.Font("Tw Cen MT", 1, 16)); // NOI18N
        btnHome.setIcon(new javax.swing.ImageIcon("C:\\Users\\Indri\\Downloads\\home.png")); // NOI18N
        btnHome.setText("Home");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        getContentPane().add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 447, 100, 43));

        btnEdit1.setBackground(new java.awt.Color(244, 245, 240));
        btnEdit1.setFont(new java.awt.Font("Tw Cen MT", 1, 16)); // NOI18N
        btnEdit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/edit.png"))); // NOI18N
        btnEdit1.setText("Edit");
        btnEdit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEdit1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnEdit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(906, 398, 100, 43));

        jTextField9.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        getContentPane().add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(908, 353, 204, 35));

        jButton1.setBackground(new java.awt.Color(244, 245, 240));
        jButton1.setFont(new java.awt.Font("Tw Cen MT", 1, 16)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Indri\\Downloads\\carts.png")); // NOI18N
        jButton1.setText("Tambah");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 440, -1, 50));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/backg.jpg"))); // NOI18N
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1260, 670));

        ShowStock.setText("jTextField1");
        getContentPane().add(ShowStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 270, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AllTotal(){
      /*
        Membuat Methode untuk mentotalkan semua belanjaan yang diambil dari setiap baris di dalam index ke-enam "Total"
        Lalu jumlahnya akan ditampilkan di jLabel TOTALSEMUA
        dan methode tersebut akan dipanggil kedalam Button Tambah, Supaya Methode nya bisa aktif
      */
      
            DefaultTableModel dataModel = (DefaultTableModel) TblTrans.getModel();
                int total = 0;
                for (int i = 0; i<TblTrans.getRowCount();i++){
                    int amount = Integer.parseInt((String)TblTrans.getValueAt(i,5));   // (i,5) maksudnya index ke-enam pada tabel "Total"
                    total += amount;
                }
                   AllTotal.setText(""+total);
    }
    
    public void MoneyChanges(){
     /*
        Membuat Methode Kembalian
        Dimana saat Karyawan memasukkan jumlah uang di dalam jTextfield saat di enter
        akan otomatis terhitung uang kembalian yang harus di kasih ke pelanggan nantinya
     */
     
            JumlahBayar = Integer.parseInt(CashMoney.getText());
            TotalBelanja = Integer.parseInt(AllTotal.getText());

            Kembalian = JumlahBayar - TotalBelanja;
            Changes.setText(""+Integer.toString(Kembalian));
    }
    
    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        // TODO add your handling code here:
        ComboIDCustAuto();
    }//GEN-LAST:event_btnPrintActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        IDAuto.setText("");
        IDEmp.setText("");
        IDCustAuto.setText("");
        ComboCust.setSelectedItem("All Cust");
        ComboProduct.setSelectedItem("All Products");
        ShowIDProduct.setText("");
        ShowPrice.setText("");
        ShowStock.setText("");
        Beli.setText("");
        SubTotal.setText("");
        CashMoney.setText("");
        Changes.setText("");
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        
        ComboIDCustAuto();
        /*
        Masuk ke Page Menu
        */

        Menu mn =  new Menu();
        mn.setVisible(true);
        mn.pack();
        mn.setLocationRelativeTo(null);
        mn.setDefaultCloseOperation(Menu.EXIT_ON_CLOSE);
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnEdit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEdit1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEdit1ActionPerformed

    private void BeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BeliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BeliActionPerformed

    private void ComboCustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboCustActionPerformed
        // TODO add your handling code here:
        ComboIDCustAuto();
    }//GEN-LAST:event_ComboCustActionPerformed

    private void ComboProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboProductActionPerformed
        // TODO add your handling code here:
        
     /*
       Dimasukkan Methode yang tadi telah dibuat, Maka baru akan terlihat Hasilnya
     */
     
        ComboShowPrice();
        ComboShowIDProduct();
        ComboShowStock();      
    }//GEN-LAST:event_ComboProductActionPerformed

    private void ShowPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ShowPriceActionPerformed

    private void BeliKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BeliKeyReleased
        // TODO add your handling code here:
        
        Integer price,jual,totalprice,stokbrng;
        price = Integer.parseInt(ShowPrice.getText());
        jual = Integer.parseInt(Beli.getText());
        stokbrng=Integer.parseInt(ShowStock.getText());
        
        /*
          Membuat fungsi dimana jika barang yang dibeli melebihi jumlah stok, maka pesanan akan 
          dibatalkan secara otomatis, dan akan muncul pesan pemberitahuan melalui JOptionPane
        */
        
        if (stokbrng < jual)
        {
            JOptionPane.showMessageDialog(rootPane, "Sorry insufficient stock");
            ShowIDProduct.setText("");
            ShowPrice.setText("");
            Beli.setText("");
            SubTotal.setText("");
        }
        else
        {
            /*
               Menghitung Subtotal pada tabel secara otomatis
            */
            
            totalprice = (price*jual);
            SubTotal.setText(String.valueOf(totalprice));
        }      
    }//GEN-LAST:event_BeliKeyReleased

    private void CashMoneyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CashMoneyKeyReleased
        // TODO add your handling code here:
        MoneyChanges();
    }//GEN-LAST:event_CashMoneyKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
      /*
        Fungsi untuk Menampilkan data barang di tabel yang dibeli setelah ditambahkan
        ini hanya disimpan secara sementara saja
      */   
            DefaultTableModel dataModel = (DefaultTableModel)TblTrans.getModel();
            List list = new ArrayList <>();
            TblTrans.setAutoCreateColumnsFromModel(true);
                list.add(IDAuto.getText());
                list.add(IDEmp.getText());
                list.add(IDCustAuto.getText());
                list.add(ShowIDProduct.getText());
                list.add(Beli.getText());
                list.add(SubTotal.getText());
                list.add(CashMoney.getText());
                list.add(Changes.getText());
            dataModel.addRow(list.toArray());
            AllTotal();
        try{
            if ((Beli.getText().equals(""))){
                JOptionPane.showMessageDialog(rootPane, "Input Quantity");
            }
            else
            {
              Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/shopet2","root","");
              cn.createStatement().executeUpdate("insert into transaction (IDTransaction, IDEmployee, IDCustomer, IDProduct, QTY, SubTotal) values"+
                                                "('"+IDAuto.getText()+
                                                "','" + IDEmp.getText()+
                                                "','" + IDCustAuto.getText()+
                                                "','" + ShowIDProduct.getText()+
                                                "','" + Beli.getText()+
                                                "','" + SubTotal.getText()+"')");
            }
        }
        catch (SQLException ex) {         
        }
        
      /*
        Untuk update stok barang/mengurangi barang setelah pembelian
      */
      
        Integer stokbarang,jumlahbeli,Sisastok;
        stokbarang=Integer.parseInt(ShowStock.getText());
        jumlahbeli=Integer.parseInt(Beli.getText());
        
        Sisastok =(stokbarang-jumlahbeli);
        
        try {
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/shopet2","root","");
            cn.createStatement().executeUpdate("update product set "
                                                   + "Stock ='"+Sisastok+
                                                   "' where IDProduct ='"+ShowIDProduct.getText()+"'");
        } catch (SQLException ex) {
                 Logger.getLogger(Transaksi.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        ShowIDProduct.setText("");
        ShowPrice.setText("");
        Beli.setText("");
        SubTotal.setText("");
        ComboProduct.setSelectedItem("All Products");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TansaksiPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TansaksiPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TansaksiPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TansaksiPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TansaksiPenjualan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AllTotal;
    private javax.swing.JTextField Beli;
    private javax.swing.JTextField CashMoney;
    private javax.swing.JLabel Changes;
    private javax.swing.JComboBox<String> ComboCust;
    private javax.swing.JComboBox<String> ComboProduct;
    private javax.swing.JTextField IDAuto;
    private javax.swing.JTextField IDCustAuto;
    private javax.swing.JTextField IDEmp;
    private javax.swing.JTextField ShowIDProduct;
    private javax.swing.JTextField ShowPrice;
    private javax.swing.JTextField ShowStock;
    private javax.swing.JTextField SubTotal;
    private javax.swing.JTable TblTrans;
    private javax.swing.JButton btnEdit1;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
    
    private void noTransAuto(){
        try {
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/shopet2","root","");
            ResultSet rs = cn.createStatement().executeQuery("SELECT * FROM transaction order by No desc");
                if (rs.next()){
                    String notrans = rs.getString("IDTransaction").substring(1);
                    String AN  = "" + (Integer.parseInt(notrans) + 1);
                    String Nol = "";
                    
                    if(AN.length()==1)
                    {Nol = "000";}
                    else if(AN.length()==2)
                    {Nol = "00";}
                    else if(AN.length()==3)
                    {Nol = "0";}
                    else if(AN.length()==4)
                    {Nol = "";}
                    
                    IDAuto.setText("T" + Nol + AN);
                } else {
                    IDAuto.setText("T0001");
                }
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void ComboBoxCust(){
     /*
       Untuk menampilkan combo Name Customer/menarik nama Customer yang telah di input dari database ke combo Box
     */
      
        try {
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/shopet2","root","");
            ResultSet rs = cn.createStatement().executeQuery("SELECT NameCust from customer order by IDCustomer asc");
                while (rs.next()){
                Object[] ob = new Object[2];
                ob[0]=rs.getString(1);

                ComboCust.addItem((String) ob[0]);
                }
        } catch (SQLException ex) {
            Logger.getLogger(TansaksiPenjualan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void ComboIDCustAuto(){
     /*
       Untuk menampilkan/menarik ID Customer ketika cmbcus di klik
     */
      
        try {
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/shopet2","root","");
            ResultSet rs = cn.createStatement().executeQuery("SELECT NameCust, IDCustomer from customer where NameCust='"+ComboCust.getSelectedItem()+"'");
                while (rs.next()){
                    Object[] ob = new Object[2];
                    ob[0]=rs.getString(1);
                    ob[1]=rs.getString(2);

                    IDCustAuto.setText((String) ob[1]);
                }
        } catch (SQLException ex) {
            Logger.getLogger(TansaksiPenjualan.class.getName()).log(Level.SEVERE, null, ex);
            }  
    }

    private void ComboBoxProduct(){
     /*
       Untuk menampilkan/menarik nama product yang telah di input dari database ke combo Box
     */
        
           try {
               Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/shopet2","root","");
               ResultSet rs = cn.createStatement().executeQuery("SELECT Product from product order by Product asc");
                    while (rs.next()){
                        Object[] ob = new Object[4];
                        ob[0]=rs.getString(1);

                   ComboProduct.addItem((String) ob[0]);
               }
           } catch (SQLException ex) {
               Logger.getLogger(TansaksiPenjualan.class.getName()).log(Level.SEVERE, null, ex);
           }
    }
    
    private void ComboShowPrice(){
      /*
        Untuk menampilkan/menarik Harga suatu product setelah ada pemilihan di dalam combo box pada methode comboproduct
      */
      
        try {
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/shopet2","root","");
            ResultSet rs = cn.createStatement().executeQuery("SELECT Product, SellingPrice, IDProduct from product where Product='"+ComboProduct.getSelectedItem()+"'");
               while (rs.next()){
                   Object[] ob = new Object[4];
                   ob[0]=rs.getString(1);
                   ob[1]=rs.getString(2);

                ShowPrice.setText((String) ob[1]);
               }
        } catch (SQLException ex) {
            Logger.getLogger(TansaksiPenjualan.class.getName()).log(Level.SEVERE, null, ex);
        }   
    }
    
    private void ComboShowIDProduct(){
      /*
        Untuk menampilkan/menarik ID suatu product setelah ada pemilihan di dalam combo box pada methode comboproduct
      */
      
        try {
               Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/shopet2","root","");
               ResultSet rs = cn.createStatement().executeQuery("SELECT Product, SellingPrice, IDProduct from product where Product='"+ComboProduct.getSelectedItem()+"'");
               while (rs.next()){
                   Object[] ob = new Object[4];
                   ob[0]=rs.getString(1);
                   ob[1]=rs.getString(2);
                   ob[2]=rs.getString(3);

                   ShowIDProduct.setText((String) ob[2]);
               }
           } catch (SQLException ex) {
               Logger.getLogger(TansaksiPenjualan.class.getName()).log(Level.SEVERE, null, ex);
           }
    }
    
    private void ComboShowStock(){
        try {
               Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/shopet2","root","");
               ResultSet rs = cn.createStatement().executeQuery("SELECT Product, SellingPrice, IDProduct , Stock from product where Product='"+ComboProduct.getSelectedItem()+"'");
               while (rs.next()){
                   Object[] ob = new Object[4];
                   ob[0]=rs.getString(1);
                   ob[1]=rs.getString(2);
                   ob[2]=rs.getString(3);
                   ob[3]= rs.getString(4);

                   ShowStock.setText((String) ob[3]);
               }
           } catch (SQLException ex) {
               Logger.getLogger(Transaksi.class.getName()).log(Level.SEVERE, null, ex);
           }
    }     
}
